# Generated by Django 6.0.4 on 2026-05-31 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_form_id'),
    ]

    operations = []
