# Generated by Django 6.0.4 on 2026-07-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_form_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
