# Generated by Django 6.0.4 on 2026-07-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_form_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
