# Generated by Django 5.2.1 on 2026-05-05 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("forms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormAccessSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "editor_access_mode",
                    models.CharField(
                        choices=[("restricted", "Restricted"), ("link", "Link")],
                        default="restricted",
                        max_length=20,
                    ),
                ),
                (
                    "responder_access_mode",
                    models.CharField(
                        choices=[
                            ("restricted", "Restricted"),
                            ("link", "Link"),
                            ("public", "Public"),
                        ],
                        default="restricted",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_settings",
                        to="forms.form",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FormAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("editor", "Editor"), ("responder", "Responder")],
                        max_length=20,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_tokens",
                        to="forms.form",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FormRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("editor", "Editor"), ("responder", "Responder")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="forms.form",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("form", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="formrole",
            index=models.Index(
                fields=["form", "role"], name="permissions_form_role_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formaccesstoken",
            index=models.Index(
                fields=["form", "scope", "is_active"],
                name="permissions_token_lookup_idx",
            ),
        ),
    ]
